// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// IJWTService is an autogenerated mock type for the IJWTService type
type IJWTService struct {
	mock.Mock
}

type IJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *IJWTService) EXPECT() *IJWTService_Expecter {
	return &IJWTService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: username, role
func (_m *IJWTService) GenerateToken(username string, role string) (string, error) {
	ret := _m.Called(username, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(username, role)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(username, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IJWTService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type IJWTService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - username string
//   - role string
func (_e *IJWTService_Expecter) GenerateToken(username interface{}, role interface{}) *IJWTService_GenerateToken_Call {
	return &IJWTService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", username, role)}
}

func (_c *IJWTService_GenerateToken_Call) Run(run func(username string, role string)) *IJWTService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *IJWTService_GenerateToken_Call) Return(_a0 string, _a1 error) *IJWTService_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IJWTService_GenerateToken_Call) RunAndReturn(run func(string, string) (string, error)) *IJWTService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: tokenStr
func (_m *IJWTService) ValidateToken(tokenStr string) (jwt.MapClaims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 jwt.MapClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (jwt.MapClaims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) jwt.MapClaims); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IJWTService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type IJWTService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *IJWTService_Expecter) ValidateToken(tokenStr interface{}) *IJWTService_ValidateToken_Call {
	return &IJWTService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenStr)}
}

func (_c *IJWTService_ValidateToken_Call) Run(run func(tokenStr string)) *IJWTService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IJWTService_ValidateToken_Call) Return(_a0 jwt.MapClaims, _a1 error) *IJWTService_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IJWTService_ValidateToken_Call) RunAndReturn(run func(string) (jwt.MapClaims, error)) *IJWTService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewIJWTService creates a new instance of IJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJWTService {
	mock := &IJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
