// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPasswordService is an autogenerated mock type for the IPasswordService type
type IPasswordService struct {
	mock.Mock
}

type IPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *IPasswordService) EXPECT() *IPasswordService_Expecter {
	return &IPasswordService_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: hashed, plain
func (_m *IPasswordService) Compare(hashed string, plain string) bool {
	ret := _m.Called(hashed, plain)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hashed, plain)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IPasswordService_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type IPasswordService_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hashed string
//   - plain string
func (_e *IPasswordService_Expecter) Compare(hashed interface{}, plain interface{}) *IPasswordService_Compare_Call {
	return &IPasswordService_Compare_Call{Call: _e.mock.On("Compare", hashed, plain)}
}

func (_c *IPasswordService_Compare_Call) Run(run func(hashed string, plain string)) *IPasswordService_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *IPasswordService_Compare_Call) Return(_a0 bool) *IPasswordService_Compare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IPasswordService_Compare_Call) RunAndReturn(run func(string, string) bool) *IPasswordService_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with given fields: password
func (_m *IPasswordService) Hash(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPasswordService_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type IPasswordService_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *IPasswordService_Expecter) Hash(password interface{}) *IPasswordService_Hash_Call {
	return &IPasswordService_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *IPasswordService_Hash_Call) Run(run func(password string)) *IPasswordService_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IPasswordService_Hash_Call) Return(_a0 string, _a1 error) *IPasswordService_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPasswordService_Hash_Call) RunAndReturn(run func(string) (string, error)) *IPasswordService_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPasswordService creates a new instance of IPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPasswordService {
	mock := &IPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
