// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "task_manager_test/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TaskUsecase is an autogenerated mock type for the TaskUsecase type
type TaskUsecase struct {
	mock.Mock
}

type TaskUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskUsecase) EXPECT() *TaskUsecase_Expecter {
	return &TaskUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *TaskUsecase) Create(ctx context.Context, t domain.Task) (domain.Task, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.Task
func (_e *TaskUsecase_Expecter) Create(ctx interface{}, t interface{}) *TaskUsecase_Create_Call {
	return &TaskUsecase_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *TaskUsecase_Create_Call) Run(run func(ctx context.Context, t domain.Task)) *TaskUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Task))
	})
	return _c
}

func (_c *TaskUsecase_Create_Call) Return(_a0 domain.Task, _a1 error) *TaskUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_Create_Call) RunAndReturn(run func(context.Context, domain.Task) (domain.Task, error)) *TaskUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TaskUsecase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TaskUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TaskUsecase_Expecter) Delete(ctx interface{}, id interface{}) *TaskUsecase_Delete_Call {
	return &TaskUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TaskUsecase_Delete_Call) Run(run func(ctx context.Context, id string)) *TaskUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TaskUsecase_Delete_Call) Return(_a0 error) *TaskUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskUsecase_Delete_Call) RunAndReturn(run func(context.Context, string) error) *TaskUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *TaskUsecase) Get(ctx context.Context, id string) (domain.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Task); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TaskUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TaskUsecase_Expecter) Get(ctx interface{}, id interface{}) *TaskUsecase_Get_Call {
	return &TaskUsecase_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *TaskUsecase_Get_Call) Run(run func(ctx context.Context, id string)) *TaskUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TaskUsecase_Get_Call) Return(_a0 domain.Task, _a1 error) *TaskUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_Get_Call) RunAndReturn(run func(context.Context, string) (domain.Task, error)) *TaskUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *TaskUsecase) List(ctx context.Context) ([]domain.Task, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TaskUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TaskUsecase_Expecter) List(ctx interface{}) *TaskUsecase_List_Call {
	return &TaskUsecase_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *TaskUsecase_List_Call) Run(run func(ctx context.Context)) *TaskUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TaskUsecase_List_Call) Return(_a0 []domain.Task, _a1 error) *TaskUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_List_Call) RunAndReturn(run func(context.Context) ([]domain.Task, error)) *TaskUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, t
func (_m *TaskUsecase) Update(ctx context.Context, t domain.Task) (domain.Task, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUsecase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TaskUsecase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.Task
func (_e *TaskUsecase_Expecter) Update(ctx interface{}, t interface{}) *TaskUsecase_Update_Call {
	return &TaskUsecase_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *TaskUsecase_Update_Call) Run(run func(ctx context.Context, t domain.Task)) *TaskUsecase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Task))
	})
	return _c
}

func (_c *TaskUsecase_Update_Call) Return(_a0 domain.Task, _a1 error) *TaskUsecase_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUsecase_Update_Call) RunAndReturn(run func(context.Context, domain.Task) (domain.Task, error)) *TaskUsecase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskUsecase creates a new instance of TaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecase {
	mock := &TaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
